{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6b7624f4-2c4d-4152-a0af-65905efc60f8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import cv2 as cv\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5b034089-6a1f-46b2-bc29-66f10a2c6654",
   "metadata": {},
   "outputs": [],
   "source": [
    "weights_path = \"face_detection_yunet_2023mar.onnx\"\n",
    "score_threshold = 0.65\n",
    "face_detector = cv.FaceDetectorYN_create(weights_path, \"\", (0, 0))\n",
    "face_detector.setScoreThreshold(score_threshold)\n",
    "\n",
    "modelPath = \"face_recognizer_fast.onnx\"\n",
    "recognizer = cv.FaceRecognizerSF.create(\n",
    "                model= modelPath,\n",
    "                config=\"\",\n",
    "                #backend_id=0,\n",
    "                #target_id=0\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3d97c79-f158-4fc3-9d0f-6f1a41fd8386",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define the path to the folder containing images\n",
    "folder_path = \"images\"\n",
    "output_folder = \"output\"\n",
    "# List all files in the folder\n",
    "files = os.listdir(folder_path)\n",
    "feat_dict = {}\n",
    "\n",
    "# Filter out image files (you can add more extensions as needed)\n",
    "image_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff']\n",
    "image_files = [f for f in files if any(f.lower().endswith(ext) for ext in image_extensions)]\n",
    "\n",
    "for image_file in image_files:\n",
    "    image_path = os.path.join(folder_path, image_file)\n",
    "    # print(f\"Processing file: {image_path}\")\n",
    "    img = cv.imread(image_path)\n",
    "    if img is None:\n",
    "        print(f\"Failed to load image: {image_path}\")\n",
    "        continue\n",
    "    height, width, _ = img.shape\n",
    "    face_detector.setInputSize((width, height))\n",
    "    _, faces = face_detector.detect(img)\n",
    "    faces = faces if faces is not None else []\n",
    "    \n",
    "    if len(faces) > 0:\n",
    "        for face1 in faces:\n",
    "            x, y, width, height = list(map(int, face1[:4]))\n",
    "            x2, y2 = x + width, y + height\n",
    "            cv.rectangle(img, (x, y), (x2, y2), (0, 0, 255), 4)\n",
    "            face_img = img[y:y + height, x:x + width]\n",
    "            face_filename = os.path.join(output_folder, f\"{os.path.splitext(image_file)[0]}_face.jpg\")\n",
    "            # cv.imwrite(face_filename, face_img)\n",
    "            \n",
    "            aligned_face_img = recognizer.alignCrop(img, face1)\n",
    "            feat_img = recognizer.feature(aligned_face_img)\n",
    "            feat_dict[face_filename[7:-4]] = feat_img"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28327676-641c-4fbb-b1d0-47f7ede5b981",
   "metadata": {},
   "source": [
    "# video face recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35ca22c8-ffd6-4560-8343-68bbd5f493f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "thresh = 0.5\n",
    "# Open the video file\n",
    "video_path = \"videos/friends4.mp4\"\n",
    "cap = cv.VideoCapture(video_path)\n",
    "\n",
    "# Check if the video was successfully opened\n",
    "if not cap.isOpened():\n",
    "    print(\"Error: Could not open video.\")\n",
    "    exit()\n",
    "while True:\n",
    "    ret, frame = cap.read()  # Read a single frame\n",
    "    if not ret:\n",
    "        break\n",
    "\n",
    "    height, width, _ = frame.shape\n",
    "    face_detector.setInputSize((width, height))\n",
    "    detected_faces_cam = face_detector.detect(frame)\n",
    "\n",
    "    if detected_faces_cam is not None and detected_faces_cam[1] is not None:\n",
    "        for face in detected_faces_cam[1]:\n",
    "            label = \"unknown\"\n",
    "            x, y, width, height = list(map(int, face[:4]))\n",
    "            x2, y2 = x + width, y + height\n",
    "            face_img = frame[y:y + height, x:x + width]\n",
    "            \n",
    "            aligned_face_cam = recognizer.alignCrop(frame, face)\n",
    "            feat_cam = recognizer.feature(aligned_face_cam)\n",
    "\n",
    "            for face_name, feat_img in feat_dict.items(): \n",
    "                result = recognizer.match(feat_cam, feat_img, cv.FaceRecognizerSF_FR_COSINE)\n",
    "\n",
    "                if result > thresh:\n",
    "                    label = face_name\n",
    "             \n",
    "            cv.putText(frame, label, (x, y - 10), cv.FONT_HERSHEY_SIMPLEX, 0.9, (0, 200, 0), 2, cv.LINE_AA)\n",
    "            cv.rectangle(frame, (x, y), (x2, y2), (0, 0, 255), 4)\n",
    "\n",
    "    cv.imshow(\"Output\", frame)\n",
    "    if cv.waitKey(1) & 0xFF == ord('q'):\n",
    "        break"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "33513ae3-e539-46e5-9d35-468188147f08",
   "metadata": {},
   "source": [
    "# real-time face recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d6831b0-f5c7-4b1f-babf-2ef123bef95f",
   "metadata": {},
   "outputs": [],
   "source": [
    "video = cv.VideoCapture(0)\n",
    "\n",
    "thresh = 0.5\n",
    "\n",
    "if (video.isOpened() == False):\n",
    "    print(\"Web Camera not detected\")\n",
    "while (True):\n",
    "    ret, frame = video.read()\n",
    "    if ret == True:\n",
    "        height, width, _ = frame.shape\n",
    "        face_detector.setInputSize((width, height))\n",
    "        detected_faces_cam = face_detector.detect(frame)\n",
    "        # print(type())\n",
    "        if len(detected_faces_cam) > 0:\n",
    "            for face in detected_faces_cam[1]:\n",
    "                # max_score = 0\n",
    "                label = \"unknown\"\n",
    "                x, y, width, height = list(map(int, face[:4]))\n",
    "                x2, y2 = x + width, y + height\n",
    "                face_img = frame[y:y + height, x:x + width]\n",
    "                print(type(face_img))\n",
    "                aligned_face_cam = recognizer.alignCrop(frame, face) #aligned_img\n",
    "                feat_cam = recognizer.feature(aligned_face_cam)\n",
    "                for face_name, feat_img in feat_dict.items(): \n",
    "                    result = recognizer.match(feat_cam, feat_img, cv.FaceRecognizerSF_FR_COSINE)\n",
    "                    print(face_name, result)\n",
    "\n",
    "                    if result > thresh:\n",
    "                        print('running')\n",
    "                        # print(face_name, result, max_score)\n",
    "                        label = face_name\n",
    "                         \n",
    "\n",
    "                cv.putText(frame, label, (x, y - 10), cv.FONT_HERSHEY_SIMPLEX, 0.9, (0, 200, 0), 2, cv.LINE_AA)\n",
    "                # cv.putText(frame, f\"Score: {thresh:.2f}\", (x, y + height + 20), cv.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2, cv.LINE_AA)\n",
    "                cv.rectangle(frame, (x, y), (x2, y2), (0, 0, 255), 4)\n",
    "        cv.imshow(\"Output\",frame)\n",
    "        if cv.waitKey(1) & 0xFF == ord('q'):\n",
    "            break\n",
    "    else:\n",
    "        break\n",
    "\n",
    "video.release()\n",
    "cv.destroyAllWindows()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
