import 'dart:convert';
import 'package:crypto/crypto.dart';

/// Shared secret used to sign QR payloads.
/// In production this should come from a secure vault / environment variable.
const String _qrSecret = 'gps-crm-qr-gate-pass-2026';

/// Builds a signed QR payload as a JSON string.
///
/// The payload includes a `sig` field — an HMAC-SHA256 digest of the core
/// data so the FrontDesk scanner can verify the QR was generated by this app
/// rather than forged externally.
String buildSignedQrPayload({
  required dynamic rollNum,
  required String studentName,
  required String className,
  required String parentName,
  required String source, // 'parent' or 'guardian'
}) {
  final data = {
    'rollNum': rollNum is int ? rollNum : int.tryParse(rollNum.toString()) ?? rollNum,
    'studentName': studentName,
    'className': className,
    'parentName': parentName,
    'source': source,
  };

  // Canonical message for HMAC: sorted key=value pairs
  final message = (data.keys.toList()..sort())
      .map((k) => '$k=${data[k]}')
      .join('|');

  final hmac = Hmac(sha256, utf8.encode(_qrSecret));
  final digest = hmac.convert(utf8.encode(message));
  data['sig'] = digest.toString();

  return jsonEncode(data);
}

/// Verifies the HMAC signature inside a decoded QR JSON payload.
///
/// Returns `true` when the `sig` matches the expected HMAC of the core data,
/// indicating the QR was generated by our app. Returns `false` otherwise.
bool verifyQrSignature(Map<String, dynamic> qrData) {
  final sig = qrData['sig'];
  if (sig == null || sig is! String || sig.isEmpty) return false;

  // Rebuild the data map *without* the signature
  final data = Map<String, dynamic>.from(qrData)..remove('sig');

  final message = (data.keys.toList()..sort())
      .map((k) => '$k=${data[k]}')
      .join('|');

  final hmac = Hmac(sha256, utf8.encode(_qrSecret));
  final expected = hmac.convert(utf8.encode(message));

  return sig == expected.toString();
}
